### ISSUE TITLE
NullPointerException: Exception ticking world

### ISSUE THREAD

**Issue by iamtpage** [svenhjol/Charm#141]
```
Time: 2019-08-08 04:47:09 GMT
Description: Exception ticking world

java.lang.NullPointerException
    at svenhjol.meson.MesonTileInventory.setLootTable(MesonTileInventory.java:127)
    at svenhjol.charm.crafting.feature.Crate.generateCrate(Crate.java:205)
    at svenhjol.charm.world.generator.AbandonedCrateGenerator.placeCrate(AbandonedCrateGenerator.java:67)
    at svenhjol.charm.world.generator.AbandonedCrateGenerator.generate(AbandonedCrateGenerator.java:48)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1020)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:985)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157)
    at net.minecraft.server.management.PlayerChunkMapEntry.providePlayerChunk(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.tick(SourceFile:147)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:227)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```

MC 1.12.2
Forge 14.23.5.2838
Charm 1.12.2-1.3.0

Steps to reproduce: walk around and generate chunks

**Comment by Velocihater** [comment]
https://paste.dimdev.org/ruguluteyi.mccrash

got this as well

**Comment by svenhjol** [comment]
Thanks for the feedback. I’ll check it out in a few hours and push a fix. In the meantime I recommend turning off the Abandoned Crates feature in config as it should prevent that code from being run and won’t negatively affect worldgen (other than crates not being generated in explored chunks)

**Comment by svenhjol** [comment]
I would be grateful if you could test this build before I publish to CF.
https://github.com/svenhjol/Charm/releases/download/1.12.2-1.3.1/Charm-1.12.2-1.3.1.jar

**Comment by iamtpage** [comment]
Will try it later tonight hopefully, hard to test because it seems to happen inconsistently

-------- Original Message --------

**Comment by svenhjol** [comment]
I managed to get it to fail pretty quickly with 1.3.0. In this new version I tried for 10 minutes of chunk generating while flying and it didn't occur.  1.3.1 has the loot tables register early which is what changed between 1.2.2 and 1.3.0.

**Comment by iamtpage** [comment]
Tested, can confirm that running around no longer crashes the server. Thank you!
