### ISSUE TITLE
Crash in vicinity of swamp hut

### ISSUE THREAD

**Issue by freecsu** [svenhjol/Charm#145]
While riding a horse in a swamp biome I experienced a crash. After restarting I walked forward some more and discovered a swamp hut generated inside of the swamp lake (above water, not sure if this is normal behavior). Crash log below.

```
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2019-08-08 11:32:47 EDT
Description: Exception ticking world

java.lang.NullPointerException
    at svenhjol.meson.MesonTileInventory.setLootTable(MesonTileInventory.java:127)
    at svenhjol.charm.crafting.feature.Crate.generateCrate(Crate.java:205)
    at svenhjol.charm.world.generator.AbandonedCrateGenerator.placeCrate(AbandonedCrateGenerator.java:67)
    at svenhjol.charm.world.generator.AbandonedCrateGenerator.generate(AbandonedCrateGenerator.java:48)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1020)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:999)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157)
    at net.minecraft.server.management.PlayerChunkMapEntry.providePlayerChunk(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.tick(PlayerChunkMap.java:226)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:227)
    at net.optifine.override.WorldServerOF.tick(WorldServerOF.java:39)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: New World
  All players: 1 total; [EntityPlayerMP['spurdo_sparde'/0, l='New World', x=593.22, y=64.22, z=769.62]]
  Chunk stats: ServerChunkCache: 541 Drop: 0
  Level seed: -7516784417908215631
  Level generator: ID 06 - quark_realistic, ver 0. Features enabled: true
  Level generator options: 
  Level spawn location: World: (224,64,244), Chunk: (at 0,4,4 in 14,15; contains blocks 224,0,240 to 239,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 1070219 game time, 1612817 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 159554 (now: false), thunder time: 111993 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_221, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 814258968 bytes (776 MB) / 2098200576 bytes (2001 MB) up to 3817865216 bytes (3641 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
  IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 13 mods loaded, 13 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID            | Version         | Source                                  | Signature                                |
       |:------ |:------------- |:--------------- |:--------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft     | 1.12.2          | minecraft.jar                           | None                                     |
       | LCHIJA | mcp           | 9.42            | minecraft.jar                           | None                                     |
       | LCHIJA | FML           | 8.0.99.99       | forge-1.12.2-14.23.5.2838-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge         | 14.23.5.2838    | forge-1.12.2-14.23.5.2838-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | foamfixcore   | 7.7.4           | minecraft.jar                           | None                                     |
       | LCHIJA | quark         | r1.6-176        | Quark-r1.6-176.jar                      | None                                     |
       | LCHIJA | autoreglib    | 1.3-32          | AutoRegLib-1.3-32.jar                   | None                                     |
       | LCHIJA | charm         | 1.12.2-1.3.0    | Charm-1.12.2-1.3.0.jar                  | None                                     |
       | LCHIJA | chunkanimator | 1.2             | ChunkAnimator-MC1.12-1.2.jar            | None                                     |
       | LCHIJA | foamfix       | 0.10.5-1.12.2   | foamfix-0.10.5-1.12.2.jar               | None                                     |
       | LCHIJA | mantle        | 1.12-1.3.3.55   | Mantle-1.12-1.3.3.55.jar                | None                                     |
       | LCHIJA | inspirations  | 1.12.2-0.2.8    | Inspirations-1.12.2-0.2.8.jar           | None                                     |
       | LCHIJA | vanillafix    | 1.0.10-SNAPSHOT | VanillaFix-1.0.10-99.jar                | None                                     |
  Loaded coremods (and transformers): Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      CharmLoadingPlugin (Charm-1.12.2-1.3.0.jar)
                                        svenhjol.charm.base.CharmClassTransformer
                                      Quark Plugin (Quark-r1.6-176.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Pulsar/inspirations loaded Pulses: - InspirationsShared (Enabled/Forced)
                                     - InspirationsBuilding (Enabled/Not Forced)
                                     - InspirationsUtility (Enabled/Not Forced)
                                     - InspirationsTools (Enabled/Not Forced)
                                     - InspirationsRecipes (Enabled/Not Forced)
                                     - InspirationsTweaks (Enabled/Not Forced)
                                     - InspirationsShared (Enabled/Forced)
  Suspected Mods: Charm (charm)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['spurdo_sparde'/0, l='New World', x=593.22, y=64.22, z=769.62]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'

```

**Comment by svenhjol** [comment]
You need to upgrade to Charm 1.3.2
