### ISSUE TITLE
Broken Dragon/Wither Immune Tags

### ISSUE THREAD

**Issue by WenXin20** [svenhjol/Charm#227]
`Minecraft v1.15.2`
`Charm v1.5.4`

Both of the above tags are broken with Charm. I'm assuming this is because runes no longer exist in 1.15.
```
[03Apr2020 23:07:47.826] [Server-Worker-4/ERROR] [net.minecraft.tags.TagCollection/]: Couldn't read block tag list minecraft:dragon_immune from minecraft:tags/blocks/dragon_immune.json in data pack Charm-1.15.2-1.5.4.jar
com.google.gson.JsonParseException: Unknown value 'charm:rune_portal'
	at net.minecraft.tags.Tag$Builder.lambda$fromJson$0(Tag.java:164) ~[?:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_231]
	at net.minecraft.tags.Tag$Builder.func_219783_a(Tag.java:163) ~[?:?]
	at net.minecraft.tags.TagCollection.lambda$reload$3(TagCollection.java:101) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_231]
```

**Comment by svenhjol** [comment]
Thanks for this, should be fixed in next version.
