### ISSUE TITLE
[1.15.2] Crash - Rendering screen

### ISSUE THREAD

**Issue by xhatz** [svenhjol/Charm#255]
Hello! On the latest version of **Charm** plus **Strange** (with **Quark**), when **aiming at a Crate in my inventory with my mouse**, the game crashes and gives me this type of error:

`java.lang.NullPointerException: Rendering screen
	at net.minecraft.tileentity.LockableLootTileEntity.func_184281_d(SourceFile:64) ~[?:?] {re:classloading}
	at net.minecraft.tileentity.LockableLootTileEntity.func_70301_a(SourceFile:92) ~[?:?] {re:classloading}
	at net.minecraftforge.items.wrapper.InvWrapper.getStackInSlot(InvWrapper.java:68) ~[?:?] {re:classloading}
	at svenhjol.charm.decoration.client.CratesClient.lambda$onRenderToolTip$0(CratesClient.java:113) ~[?:1.15.2-1.5.7] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?] {re:classloading}
	at svenhjol.charm.decoration.client.CratesClient.onRenderToolTip(CratesClient.java:79) ~[?:1.15.2-1.5.7] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_252_CratesClient_onRenderToolTip_PostText.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.1.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.1.0-service.jar:?] {}
	at net.minecraftforge.fml.client.gui.GuiUtils.drawHoveringText(GuiUtils.java:398) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.gui.GuiUtils.drawHoveringText(GuiUtils.java:256) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.screen.Screen.renderTooltip(Screen.java:139) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.renderTooltip(Screen.java:116) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_191948_b(ContainerScreen.java:149) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.render(SourceFile:95) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[minecraft-1.15.2-client.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.1.63-launcher.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:39) [ForgeWrapper-1.4.1.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}`

Thank you for your work, your mods are absolutely amazing!

### Additional informations
- The crate was broken in creative and in a vault, on a server (only the client crashes).

**Comment by svenhjol** [comment]
Thanks for the report.

**Comment by svenhjol** [comment]
Should be ok in 1.5.9. Please reopen if necessary
