### ISSUE TITLE
Crash during the world generation with last Quark-r1.5-147

### ISSUE THREAD

**Issue by SAIANBY** [svenhjol/Charm#31]
Incompatible with last Quark-r1.5-147. Crash during the world generation.

java.lang.NoSuchFieldError: CAPABILITY
	at vazkii.quark.base.capability.CapabilityHandler.attachTileCapabilities(CapabilityHandler.java:92)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_279_CapabilityHandler_attachTileCapabilities_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:691)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:655)
	at net.minecraft.tileentity.TileEntity.<init>(TileEntity.java:478)
	at svenhjol.meson.MesonTile.<init>(MesonTile.java:13)
	at svenhjol.meson.MesonTileInventory.<init>(MesonTileInventory.java:23)
	at svenhjol.charm.crafting.tile.TileCrate.<init>(TileCrate.java:15)
	at svenhjol.charm.crafting.block.BlockCrate.createTileEntity(BlockCrate.java:190)
	at svenhjol.charm.crafting.block.BlockCrate.createTileEntity(BlockCrate.java:34)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:623)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at svenhjol.charm.crafting.feature.Crate.generateCrate(Crate.java:162)
	at svenhjol.charm.loot.feature.AbandonedCrates.generateCrate(AbandonedCrates.java:104)
	at svenhjol.charm.loot.feature.AbandonedCrates.onPopulate(AbandonedCrates.java:62)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1727_AbandonedCrates_onPopulate_Populate.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.terraingen.TerrainGen.populate(TerrainGen.java:55)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:453)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:186)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)

**Comment by Hubry** [comment]
Minimal reproduction: https://paste.ee/p/pEp1k

You are repacking Quark's API in your mod, which you should not do because if something changes upstream, like a field or method gets added in those classes, but the old version gets loaded instead, you will get mysterious crashes from innocent-looking code. 

In this case, some of Quark's API stuff was converted into capabilities, wrapping implementations of those classes for compatibility, but the old version of the class was loaded instead.

Please remove all the API classes (you are already pulling Quark through maven, btw there's an API jar on there nowadays too) and use `@Optional.Interface` to strip the interface from the tile if Quark is not loaded (or use the capability event handled only if Quark's loaded to attach the cap). Consider doing the same with InvTweaks's API.
