### ISSUE TITLE
Mod conflict with Bookshelving mod

### ISSUE THREAD

**Issue by RDKRACZ** [svenhjol/Charm#342]
Reported to P3NG00 too - https://github.com/P3NG00/MoreBookshelvesFabricMod/issues/4
crash report - does not generate
latest.log - https://hatebin.com/bdaayqfrrw

**Comment by svenhjol** [comment]
Please check fixed in https://github.com/svenhjol/Charm/releases/download/2.0.3-fabric/charm-fabric-1.16.3-2.0.3-hotfix2.jar (also available on CF)

**Comment by RDKRACZ** [comment]
Doesn't work with Charm 2.1.0. Should I check with the older - 2.0.3 hotfix2?

**Comment by svenhjol** [comment]
Actually this error looks like a direct conflict, both mods are patching the enchantment table code

**Comment by RDKRACZ** [comment]
Hi, so what about this?
Charm 2.1.4
Crash report doesn't generate.
[Latest] latest.log:
```
[02:42:15] [main/INFO]: Loading for game Minecraft 1.16.4
[02:42:15] [main/INFO]: [FabricLoader] Loading 48 mods: fabric-renderer-api-v1@0.3.3+6a2618f53a, fabric-screen-handler-api-v1@1.1.0+6a2618f53a, minecraft@1.16.4, fabric-networking-blockentity-v0@0.2.7+a03e98793a, fabric-keybindings-v0@0.2.0+6a2618f53a, fabric-command-api-v1@1.0.9+6a2618f53a, fabricloader@0.10.8, fabric-tool-attribute-api-v1@1.2.5+6a2618f53a, fabric-structure-api-v1@1.1.1+f1d8af063a, fabric-renderer-indigo@0.4.3+6a2618f53a, fabric-containers-v0@0.1.9+a03e98793a, fabric-object-builder-api-v1@1.9.2+6a2618f53a, fabric-dimensions-v1@2.0.1+9a6c75813a, com_electronwill_night-config_toml@3.6.2, fabric-events-interaction-v0@0.4.1+6a2618f53a, fabric-item-api-v1@1.2.0+6a2618f53a, fabric-crash-report-info-v1@0.1.2+b7f9825d3a, fabric-game-rule-api-v1@1.0.3+a4467d2a3a, fabric-api-base@0.2.0+ab87788d3a, fabric-rendering-v0@1.1.1+6a2618f53a, fabric-rendering-v1@1.4.0+6a2618f53a, fabric-key-binding-api-v1@1.0.1+730711c63a, fabric-rendering-data-attachment-v1@0.1.4+6a2618f53a, fabric-resource-loader-v0@0.3.2+1944f3e03a, fabric-textures-v0@1.0.5+6a2618f53a, com_electronwill_night-config_core@3.6.2, fabric-content-registries-v0@0.2.0+e77439c73a, fabric-tag-extensions-v0@1.1.0+e77439c73a, fabric-rendering-fluids-v1@0.1.12+6a2618f53a, fabric-biome-api-v1@3.1.0+2e23b97c3a, com_moandjiezana_toml_toml4j@0.7.2, fabric-registry-sync-v0@0.7.2+a03e98793a, fabric-commands-v0@0.2.0+6a2618f53a, fabric-blockrenderlayer-v1@1.1.4+6a2618f53a, morebookshelves@0.0.1, fabric-lifecycle-events-v1@1.2.0+ffb68a873a, fabric-mining-levels-v0@0.1.2+6a2618f53a, fabric-renderer-registries-v1@2.2.0+6a2618f53a, fabric-networking-api-v1@1.0.0+4358fbc63a, fabric-loot-tables-v1@1.0.1+6a2618f53a, charm@2.1.4, fabric-events-lifecycle-v0@0.2.0+6a2618f53a, fabric@0.28.0+1.16, fabric-particles-v1@0.2.2+6a2618f53a, fabric-models-v0@0.1.1+6a2618f53a, fabric-item-groups-v0@0.2.1+6a2618f53a, fabric-networking-v0@0.3.0+a03e98793a, fabric-object-builders-v0@0.7.1+6a2618f53a
[02:42:15] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/k0rr/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[02:42:15] [main/WARN]: @Mixin target net/minecraft/class_3353$class_3354 is public in charm.mixins.json:MineshaftGeneratorMixin and should be specified in value
[02:42:15] [main/WARN]: @Mixin target net/minecraft/class_3353$class_3357 is public in charm.mixins.json:MineshaftGeneratorMixin and should be specified in value
[02:42:17] [main/FATAL]: Mixin apply failed charm.mixins.json:EnchantmentScreenHandlerMixin -> net.minecraft.class_1718: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_1718::hookOnContentChanged with priority 1000 cannot inject into net/minecraft/class_1718::method_7609(Lnet/minecraft/class_1263;)V merged by com.p3ng00.morebookshelves.mixin.EnchantmentScreenHandlerMixin with priority 1000 [PREINJECT Applicator Phase -> charm.mixins.json:EnchantmentScreenHandlerMixin -> Prepare Injections ->  -> handler$zec000$hookOnContentChanged(Lnet/minecraft/class_1263;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_1799;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_1718::hookOnContentChanged with priority 1000 cannot inject into net/minecraft/class_1718::method_7609(Lnet/minecraft/class_1263;)V merged by com.p3ng00.morebookshelves.mixin.EnchantmentScreenHandlerMixin with priority 1000 [PREINJECT Applicator Phase -> charm.mixins.json:EnchantmentScreenHandlerMixin -> Prepare Injections ->  -> handler$zec000$hookOnContentChanged(Lnet/minecraft/class_1263;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_1799;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.10.8.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-loader-0.10.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
	at net.minecraft.class_2246.<clinit>(class_2246.java:359) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_3523.<clinit>(class_3523.java:13) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_5471.<clinit>(class_5471.java:11) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_5458.method_30573(class_5458.java:44) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) [?:1.8.0_275]
	at net.minecraft.class_5458.<clinit>(class_5458.java:74) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:237) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) [intermediary-minecraft-1.16.4-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

```
