### ISSUE TITLE
[1.16.3 fabric]Crash in startup

### ISSUE THREAD

**Issue by MarinaMarissa** [svenhjol/Charm#344]
log:
---- Minecraft Crash Report ----
// My bad.

Time: 20-10-30 下午8:23
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'charm'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:423)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_4668.<clinit>(class_4668.java:80)
	at net.minecraft.class_4696.method_23685(class_4696.java:21)
	at net.minecraft.class_4696$$Lambda$3021/1705898735.accept(Unknown Source)
	at net.minecraft.class_156.method_654(class_156.java:354)
	at net.minecraft.class_4696.<clinit>(class_4696.java:20)
	at svenhjol.meson.mixin.accessor.RenderLayersAccessor.getBlocks(RenderLayersAccessor.java)
	at svenhjol.charm.module.VariantLadders.lambda$clientRegister$1(VariantLadders.java:41)
	at svenhjol.charm.module.VariantLadders$$Lambda$3020/91779430.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at svenhjol.charm.module.VariantLadders.clientRegister(VariantLadders.java:40)
	at svenhjol.meson.Meson$$Lambda$3019/649928351.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at svenhjol.meson.MesonMod.eachModule(MesonMod.java:33)
	at svenhjol.meson.Meson.lambda$go$0(Meson.java:35)
	at svenhjol.meson.Meson$$Lambda$2997/270683459.accept(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.forEach(Unknown Source)
	at svenhjol.meson.Meson.go(Meson.java:32)
	at svenhjol.charm.Charm.onInitialize(Charm.java:24)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2364/360728721.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_1059::method_18163(Lnet/minecraft/class_3300;Ljava/util/stream/Stream;Lnet/minecraft/class_3695;I)Lnet/minecraft/class_1059$class_4007; has incompatible changes at opcode 157 in callback net/minecraft/class_1059::hookStitch.
Expected: [Ljava/util/Set;]
   Found: [I]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:447)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:423)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7912350520 bytes (7545 MB) / 8696889344 bytes (8294 MB) up to 8696889344 bytes (8294 MB)
	CPUs: 8
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx8294m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.6
		adventurez: AdventureZ 1.1.3
		allure: Allure 1.2.7
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		appleskin: AppleSkin 1.0.11
		autoconfig1u: Auto Config v1 Updated 3.2.2
		bebooks: Better Enchanted Books 1.1.4
		bettercaves: YUNG's Better Caves 1.16.2-1.0.3
		betterend: Better End 0.4.1-alpha
		betterf3: BetterF3 1.1.1
		betternether: Better Nether 4.1.5
		blue_endless_jankson: jankson 1.2.0
		byg: BYG 1.1-BETA-v4
		campanion: Campanion 1.2.0+build.39
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.0.2
		cardinal-components-base: Cardinal Components API (base) 2.6.0
		cardinal-components-entity: Cardinal Components API (entities) 2.6.0
		cardinal-components-item: Cardinal Components API (items) 2.6.0
		cardinal-components-util: Cardinal Components API (utilities) 2.6.0
		charm: Charm 2.0.3
		cheatless: Cheatless 0.1.0
		cherishedworlds: Cherished Worlds 1.2.0-1.16.3
		cloth-api: Cloth API 1.4.8
		cloth-armor-api-v1: Cloth Armor API v1 1.4.8
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.8
		cloth-common-events-v1: Cloth Common Events v1 1.4.8
		cloth-config2: Cloth Config v4 4.8.2
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.8
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.8
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.8
		cloth-scissors-api-v1: Cloth Scissors API v1 1.4.8
		cloth-utils-v1: Cloth Utils v1 1.4.8
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compactstatuseffects: Compact Status Effects 1.2.3
		cotton: Cotton 1.0.7
		cotton-commons: Cotton Commons 1.0.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		curioofundying: Curio of Undying 1.1.0-1.16.3
		curios: Curios API 0.0.8-1.16.3
		custom_piglin_bartering: Custom Piglin Bartering 1.0.5+MC1.16-1.16.3
		customskinloader: CustomSkinLoader 14.12
		dataloader: Data Loader 2.1.0+mc1.16.1
		daylight_mobs: Daylight Mobs 1.0.0
		de_javagl_obj: obj 0.3.0
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		disablecustomworldsadvice: Disable Custom Worlds Advice 1.1
		doom: Doom Fabric 3.3.2
		dungeonsmod: Dungeons Mod Lite 1.16.2-0.8.0.0-alpha8
		durabilityviewer: Giselbaers Durability Viewer 1.16.2-fabric0.17.2-1.8.7
		dynamicfps: Dynamic FPS 1.1.4
		eggtab: Egg Tab 1.3.1+1.16-fabric
		eldritch_mobs: Eldritch Mobs 1.5.1
		fabric: Fabric API 0.24.3+build.414-1.16
		fabric-api-base: Fabric API Base 0.2.0+9f0fb4b895
		fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a95
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-diagonal-panes: Fabric Diagonal Panes 0.3.1
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a95
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a95
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab95
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a95
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a95
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a95
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a95
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a95
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+2b46237995
		fabricloader: Fabric Loader 0.10.5+build.213
		fastbench: FastBench 2.3
		fastfurnace: FastFurnace 2.3
		fiber: fiber 0.23.0-1
		foml: FOML 1.3.0
		gbfabrictools: GBfabrictools 1.2.3+1.16.2
		geckolib: Geckolib 2.0.0
		greater_eye: Greater Eye of Ender 1.1.1
		hardcorequesting: Hardcore Questing Mode 1.16.2+5.5.2
		i18nreborn: I18nreborn fabric-1.15
		imblocker: IMBlockerFabric 1.0.1
		imm_ptl_core: Immersive Portals Core 0.40
		immersive_portals: Immersive Portals 0.40
		inventoryprofiles: Inventory Profiles 0.4.2
		invtrashslot: InvTrashSlot 1.0.1
		jankson: Jankson 3.0.1+j1.2.0
		kyrptconfig: Kytpt Config 1.1.4-1.16
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		libblockattributes_core: LibBlockAttributes (Core) 0.8.1
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.1
		libgui: LibGui 3.0.0-beta.1+1.16.2-rc2
		libstructure: LibStructure 1.5
		lightoverlay: Light Overlay 5.5.0
		malilib: MaLiLib 0.10.0-dev.21+arne.1
		materialisation: Materialisation 3.0.3
		minecraft: Minecraft 1.16.3
		minihud: MiniHUD 0.19.0-dev.20200912.222204
		minimalmenu: MinimalMenu 1.16.3-0.0.4
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 1.14.6+build.31
		moretotems: More Totems 2.7.0
		mostructures: Mo' Structures 1.0.0-pre3+mc.1.16.2
		mtca: More Totems Curios Addon 1.0.0
		notchify: Notchify 0.2.3
		open2lan: Open To Lan 0.0.3
		optifabric: OptiFabric 1.6.4
		orderly: Orderly 2.0.0-alpha.10-1.16
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		patchouli: Patchouli 1.16.2-44-FABRIC
		phosphor: Phosphor 0.6.0-SNAPSHOT
		polymorph: Polymorph 0.0.5-1.16.3
		randomtitle: RandomTitle 1.5
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		repurposed_structures: Repurposed Structures 1.16.3-1.6.8
		ring_of_enderchest: Ring of Enderchest 1.0.24
		ringsofascension: Rings of Ascension 1.0.7
		roughlyenoughitems: Roughly Enough Items 5.2.3
		roughlyenoughitems-api: REI (API) 5.2.3
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.2.3
		roughlyenoughitems-runtime: REI (Runtime) 5.2.3
		shulkerboxtooltip: Shulker Box Tootip 2.1.1-beta.1+1.16.2-rc2
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		totemplus: Totem Plus 1.0.1
		trinkets: Trinkets 2.6.6
		ttg_fallfest: FallFest 2020 0.1.1
		voxelmap: VoxelMap 1.10.10
		voyager: Voyager 1.0.0
		waila: Hwyla 1.9.22
		zoob: Monster Of The Ocean Depths 1.0.0
	Patchouli open book context: n/a
	Launched Version: 1.16.3-Fabric 0.10.5.213
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.16.3_HD_U_G4_pre2
	OptiFine Build: 20201007-190609
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 0

**Comment by svenhjol** [comment]
This hotfix should sort it out. https://github.com/svenhjol/Charm/releases/download/2.0.3-fabric/charm-fabric-1.16.3-2.0.3-hotfix2.jar
