### ISSUE TITLE
[20w46a] Crash on start 

### ISSUE THREAD

**Issue by kpv8** [svenhjol/Charm#364]
**Required - Versions**
* Charm version - 2.1.1
* Minecraft version - 20w46a
* Loader - `Fabric`

**Description**
Just placed the mod in mods folder and this crash happens, when I removed it, problem was gone, tested with just fabric api no other mods crash still occurs. 

**Optional: Stacktrace/Screenshots**
[21:16:01] [main/INFO]: Loading for game Minecraft 20w46a
[21:16:01] [ForkJoinPool-1-worker-2/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[21:16:02] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.2.0+9f0fb4b83b, also found 0.2.0+9f0fb4b83a
 - Conflicting versions found for fabric-particles-v1: used 0.2.2+fb0d9b0e3a, also found 0.2.2+fb0d9b0e3b
[21:16:02] [main/INFO]: [FabricLoader] Loading 56 mods: fabric-renderer-api-v1@0.3.3+a4467d2a3b, fabric-keybindings-v0@0.2.0+3fa9f7c53b, fabricloader@0.10.6+build.214, cavebiomes@0.6.0, fabric-structure-api-v1@1.1.1+3e817a623b, falling_tree@2.5.1, fabric-containers-v0@0.1.8+045df74f3b, fabric-object-builder-api-v1@1.10.2+df3673f03b, fabric-game-rule-api-v1@1.0.4+3e817a623b, bettercaves@20w45a-0.1.4, fabric-api-base@0.2.0+9f0fb4b83b, fabric-rendering-data-attachment-v1@0.1.4+f8ac1db23b, fabric-textures-v0@1.0.5+a4467d2a3b, fabric-rendering-fluids-v1@0.1.12+f8ac1db23b, com_moandjiezana_toml_toml4j@0.7.2, fabric-blockrenderlayer-v1@1.1.4+c6a8ea893b, fabric-lifecycle-events-v1@1.3.2+24947c8d3b, mo_glass@1.5-MC20w46a, fabric-renderer-registries-v1@3.0.2+df3673f03b, fabric-loot-tables-v1@1.0.2+df3673f03b, fabric@0.25.6+1.17, fabric-particles-v1@0.2.2+fb0d9b0e3a, fabric-networking-v0@0.1.10+e00ecb5f3b, fabric-screen-handler-api-v1@1.1.3+df3673f03b, minecraft@1.17-alpha.20.46.a, fabric-networking-blockentity-v0@0.2.6+3e817a623b, modmenu@2.0.0-beta.1+build.2, illuminations@1.2.4, jankson@3.0.0+j1.2.0, cloth-basic-math@0.5.1, fabric-command-api-v1@1.0.9+a4467d2a3b, fabric-tool-attribute-api-v1@1.2.7+df3673f03b, fabric-renderer-indigo@0.4.4+3e817a623b, com_electronwill_night-config_toml@3.6.2, fabric-item-api-v1@1.2.1+df3673f03b, fabric-crash-report-info-v1@0.1.2+b7f9825d3b, fabric-events-interaction-v0@0.4.3+df3673f03b, fabric-rendering-v0@1.1.1+f8ac1db23b, fabric-rendering-v1@1.3.1+f8ac1db23b, fabric-key-binding-api-v1@1.0.1+730711c63b, cloth-config2@4.8.3, fabric-resource-loader-v0@0.3.3+df3673f03b, autoconfig1u@3.3.1, chainmail@0.5.0, expandedstorage@6.0.1, fabric-content-registries-v0@0.1.9+059ea8663b, fabric-tag-extensions-v0@1.0.4+3e817a623b, fabric-biome-api-v1@3.0.1+df3673f03b, fabric-registry-sync-v0@0.6.1+a4467d2a3b, fabric-commands-v0@0.2.0+52d308363b, fabric-mining-levels-v0@0.1.2+b764ce993b, charm@2.1.1, fabric-events-lifecycle-v0@0.2.0+16acbe5b3b, fabric-models-v0@0.1.1+f8ac1db23b, fabric-item-groups-v0@0.2.1+a4467d2a3b, fabric-object-builders-v0@0.7.2+96d1e9ea3b
[21:16:02] [main/WARN]: Mod `bettercaves` (20w45a-0.1.4) does not respect SemVer - comparison support is limited.
[21:16:02] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/kpv81/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[21:16:02] [main/WARN]: Reference map 'charm.mixins.refmap.json' for charm.mixins.json could not be read. If this is a development environment you can ignore this message
[21:16:02] [main/WARN]: Error loading class: net/minecraft/structure/MineshaftGenerator$MineshaftCorridor (java.lang.ClassNotFoundException: net/minecraft/structure/MineshaftGenerator$MineshaftCorridor)
[21:16:02] [main/WARN]: @Mixin target net.minecraft.structure.MineshaftGenerator$MineshaftCorridor was not found charm.mixins.json:MineshaftGeneratorMixin
[21:16:02] [main/WARN]: Error loading class: net/minecraft/structure/MineshaftGenerator$MineshaftRoom (java.lang.ClassNotFoundException: net/minecraft/structure/MineshaftGenerator$MineshaftRoom)
[21:16:02] [main/WARN]: @Mixin target net.minecraft.structure.MineshaftGenerator$MineshaftRoom was not found charm.mixins.json:MineshaftGeneratorMixin
[21:16:02] [main/WARN]: Error loading class: net/minecraft/structure/MineshaftGenerator$MineshaftPart (java.lang.ClassNotFoundException: net/minecraft/structure/MineshaftGenerator$MineshaftPart)
[21:16:02] [main/WARN]: @Mixin target net/minecraft/structure/MineshaftGenerator$MineshaftPart was not found charm.mixins.json:accessor.MineshaftGeneratorAccessor
[21:16:02] [main/FATAL]: Mixin apply failed charm.mixins.json:accessor.BlockAccessor -> net.minecraft.class_2248: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching translationKey:Ljava/lang/String; in net/minecraft/class_2248 for charm.mixins.json:accessor.BlockAccessor->@Accessor[FIELD_SETTER]::setTranslationKey(Ljava/lang/String;)V [INJECT Applicator Phase -> charm.mixins.json:accessor.BlockAccessor -> Apply Accessors ->  -> Locate -> charm.mixins.json:accessor.BlockAccessor->@Accessor[FIELD_SETTER]::setTranslationKey(Ljava/lang/String;)V]
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching translationKey:Ljava/lang/String; in net/minecraft/class_2248 for charm.mixins.json:accessor.BlockAccessor->@Accessor[FIELD_SETTER]::setTranslationKey(Ljava/lang/String;)V [INJECT Applicator Phase -> charm.mixins.json:accessor.BlockAccessor -> Apply Accessors ->  -> Locate -> charm.mixins.json:accessor.BlockAccessor->@Accessor[FIELD_SETTER]::setTranslationKey(Ljava/lang/String;)V]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:518) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:501) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:475) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1318) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1051) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.10.6+build.214.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.10.6+build.214.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.minecraft.class_2378.<clinit>(class_2378.java:164) [intermediary-fabric-loader-0.10.6+build.214-20w46a.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:43) [intermediary-fabric-loader-0.10.6+build.214-20w46a.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) [intermediary-fabric-loader-0.10.6+build.214-20w46a.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.6+build.214.jar:?]

**Comment by svenhjol** [comment]
Thanks for this report. Something went wrong when packaging, and it didn't get the correct refmap or toml libraries. Please try this version and let me know. https://github.com/svenhjol/Charm/releases/download/2.1.1/charm-fabric-1.17-20w46a-2.1.1.jar

**Comment by kpv8** [comment]
Now after installing this version from link, it loads without a problem.

**Comment by svenhjol** [comment]
Thanks for testing. I'll release this version today
