### ISSUE TITLE
No Such Method func_70016_h(DDD)V

### ISSUE THREAD

**Issue by TzarAnthony** [svenhjol/Charm#380]
**Versions**
* Charm version - 2.1.1
* Minecraft version - 1.6.4
* Loader - Forge

**Required - Description**
Server crash due to NoSuchMethodError

java.lang.NoSuchMethodError: svenhjol.charm.entity.CoralSquidEntity.func_70016_h(DDD)V

**Optional: Steps To Reproduce**
I teleported to a spot in a coral reef ocean and the game crashed

**Optional: Stacktrace/Screenshots**
Stacktrace:
	at svenhjol.charm.entity.CoralSquidEntity.func_70636_d(CoralSquidEntity.java:223) ~[charm:2.1.1] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf:fml:astralsorcery:water_movement_slowdown_prevention,pl:mixin:APP:the_bumblezone.mixins.json:MobHitMixin,pl:mixin:APP:charm.mixins.json:LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:HoneyShieldCooldownMixin,pl:mixin:APP:the_bumblezone.mixins.json:HoneyShieldPreferredSlotMixin,pl:mixin:APP:charm.mixins.json:accessor.MobEntityAccessor,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMobEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:immersiveengineering:IE block update callback,pl:mixin:APP:charm.mixins.json:accessor.ServerWorldAccessor,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}

**Comment by Mourdraug** [comment]
Okay so I messed around a bit and from what I can see this is not charm's issue but forge invalidly reobfuscates BlockPos.getCoordinatesAsString() method used here. Luckily it's only used for a debug, so I just commented these two lines out and recompiled and it works.
https://github.com/svenhjol/Charm/blob/1.16-forge/src/main/java/svenhjol/charm/entity/CoralSquidEntity.java#L95-L96

**Comment by Mourdraug** [comment]
This seem to be an issue with charm being compiled with older forge version than one being used, but honestly this repo is a mess and I don't feel like digging through thousand's of commits to find that 2.1.1 hotfix 4 - forge point (only fabric version is tagged), but if you were to find it and recompile with newer forge version it might fix it.

**Comment by svenhjol** [comment]
Thanks, I'll apply your fix to 2.1.2 which is due out tomorrow. There are no more hotfixes for 2.1.1.

**Comment by Mourdraug** [comment]
FYI I'm not sure about what caused this in the first place but I recompiled 2.1.1-forge-hotfixes branch without bumping forge version and it was enough to fix this for me, so... werid.
