### ISSUE TITLE
crashes minecraft launcher with "exit code 0"

### ISSUE THREAD

**Issue by nikishev1** [svenhjol/Charm#447]
Versions
* Charm version - 2.2.0
* Minecraft version - 1.6.4`

Description
with this mod enabled, when I launch minecraft launcher fabric profile it won't launch and it says "exit code 0".

Optional: Steps To Reproduce
enable this mod and launch minecraft

Optional: Stacktrace/Screenshots
```
[Info: 2020-12-25 17:56:53.5134746: GameCallbacks.cpp(162)] Game/smoothboot (main) Info Smooth Boot config initialized
[Info: 2020-12-25 17:56:55.1492960: GameCallbacks.cpp(162)] Game/mixin (main) Warn @Redirect conflict. Skipping charm.mixins.json:EnchantingTableBlockMixin->@Redirect::hookRandomDisplayTick(Lnet/minecraft/class_2680;Lnet/minecraft/class_2248;)Z with priority 1000, already redirected by atbyw.mixins.json:EnchantingTableBlockMixin->@Redirect::redirectIsOf(Lnet/minecraft/class_2680;Lnet/minecraft/class_2248;)Z with priority 1000
[Info: 2020-12-25 17:56:55.2857605: GameCallbacks.cpp(162)] Launcher/launcher (main) Info 

Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)

	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)

	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

Caused by: java.lang.reflect.InvocationTargetException

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)

	... 2 more

Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)

	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)

	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)

	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)

	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)

	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

	at net.minecraft.class_3523.<clinit>(class_3523.java:13)

	at net.minecraft.class_5471.<clinit>(class_5471.java:11)

	at net.minecraft.class_5458.method_30573(class_5458.java:44)

	at net.minecraft.class_5458.method_30566(class_5458.java:75)

	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)

	at net.minecraft.class_5458.<clinit>(class_5458.java:74)

	at net.minecraft.class_2378.<clinit>(class_2378.java:237)

	at net.minecraft.class_2966.method_12851(class_2966.java:42)

	at net.minecraft.client.main.Main.main(Main.java:137)

	... 7 more

Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector hookRandomDisplayTick(Lnet/minecraft/class_2680;Lnet/minecraft/class_2248;)Z in charm.mixins.json:EnchantingTableBlockMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap charm-fabric-1.16.4-refmap.json

	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)

	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)

	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)

	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)

	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)

	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)

	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)

	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)

	... 22 more


```

**Comment by ridjack** [comment]
What other mods do you have enabled?

**Comment by ridjack** [comment]
Looks like there might be a conflict between "All The Blocks You Want" and Charm. Try removing that mod and see if this solves the crash.

**Comment by nikishev1** [comment]
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\mob-proof-crystals-1.1.0.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\Modern-Industrialization-0.3.9.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\modmenu-1.14.13+build.19.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\mostructures-1.0.1+mc.1.16.4.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\nostrip-1.2.0-1.16.2+.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\phonos-0.1.1-beta.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\phosphor-fabric-mc1.16.3-0.7.0+build.10.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\red-bits-1.5.0.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\RoughlyEnoughItems-5.8.10.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\simpleplanes-fabric-3.2.3.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\SimpleVoidWorld-5.0.0.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\smoothboot-fabric-1.16-1.3.1.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\sodium-fabric-mc1.16.3-0.1.0.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\terrestria-2.1.5+build.28.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\traverse-3.2.0+build.17.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\unearthed-1.0.5.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\world_blender-1.16.4-1.0.11.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\XaerosWorldMap_1.11.4_Fabric_1.16.4.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\appliedenergistics2-8.1.0.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\ash-1.1.11.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\atbyw-1.16.4-1.3.4.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\automated-crafting-1.3.14+MC1.16.2-1.16.4.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\AutoPlanter-16.3.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\beenfo-1.16.4-fabric0.25.1-1.3.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\BetterCaves-fabric-1.16.2-1.0.3.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\better-nether-5.0.4.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\better-wandering-trader-1.6.2.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\byg-1.1.3.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\campanion-1.3.1+build.51.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\cinderscapes-1.3.0+build.51.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\crumbs-1.0.6+1.16.4-fabric.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\darkness-mc116-1.6.57.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\fabric-api-0.28.4+1.16.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\gilded-netherite-fabric-1.6.0.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\inventorytabs-0.3.0-1.16.4.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\Just_Another_Redstone_Gate_Mod-1.2.0.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\launchers-mod-1.16-2.2.0.jar"
"C:\Users\nkshv\AppData\Roaming\.minecraft\mods\lithium-fabric-mc1.16.4-0.6.0.jar"

**Comment by nikishev1** [comment]
yes i have all the block you want i will delete it

**Comment by ridjack** [comment]
Try that first and see if it helps, yes.

If that doesn't help, you'll have to try to find the conflict. Remove half your list and see if it boots. Then try the other half. Rinse and repeat until you narrow it down.

**Comment by Coranthes** [comment]
Don't do this in your existing world, of course

**Comment by ridjack** [comment]
It's definitely a conflict. We'll track it in #448 ; watch there for a fix.
