### ISSUE TITLE
Placing a custom chest (spruce or others) disconnect the client

### ISSUE THREAD

**Issue by Porcy** [svenhjol/Charm#464]
Versions
* Charm version - 2.2.1
* Minecraft version - 20w51a

Description

Placing custom chest or crate disconnect the client. You can still use it after relogging.

Log:
"Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at svenhjol.charm.module.AutoRestock.findReplacement(AutoRestock.java:76) ~[charm-fabric-1.17-20w51a-2.2.1.jar:?]
	at svenhjol.charm.module.AutoRestock.handlePlayerTick(AutoRestock.java:45) ~[charm-fabric-1.17-20w51a-2.2.1.jar:?]
	at svenhjol.charm.event.PlayerTickCallback.lambda$static$0(PlayerTickCallback.java:10) ~[charm-fabric-1.17-20w51a-2.2.1.jar:?]
	at net.minecraft.class_1657.handler$zch001$hookTick(class_1657.java:2326) ~[intermediary-server.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:321) ~[intermediary-server.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:416) ~[intermediary-server.jar:?]"

**Comment by svenhjol** [comment]
Fixed in 21w08b
