### ISSUE TITLE
[CTD] NPE when exploring, Crate disabled, AbandonedCrate enabled

### ISSUE THREAD

**Issue by drakray** [svenhjol/Charm#57]
https://pastebin.com/R0SXkmMz
```
java.lang.NullPointerException: Exception ticking world
	at svenhjol.charm.world.generator.AbandonedCrateGenerator.placeCrate(AbandonedCrateGenerator.java:66)
	at svenhjol.charm.world.generator.AbandonedCrateGenerator.generate(AbandonedCrateGenerator.java:48)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:985)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_180495_p(World.java:911)
	at biomesoplenty.common.block.BlockBOPGrass.spreadGrass(BlockBOPGrass.java:313)
	at biomesoplenty.common.block.BlockBOPGrass.func_180650_b(BlockBOPGrass.java:288)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
```

Here's my config too: https://pastebin.com/B9CXYgjd

I had Crate=false, but AbandonedCrates=true, and exploring outside preGened got me this little CTD

**Comment by drakray** [comment]
Using:
MC 1.12.2
Forge 2838
Charm 1.12.2-1.1.0
Buncha Others, listed in log
