### ISSUE TITLE
Totem of Preserving not showing up

### ISSUE THREAD

**Issue by jaded33** [svenhjol/Charm#628]
Read me first!
1. FABRIC
2. No Optifabric or Iris installed
Versions
* Charm version - 3.3.0
* Minecraft version - 1.17

Description
Totem of Preserving is no longer appearing after death.  My config is still set to True for ToP and to keep XP after death.  Using a heavily modded client and server.  My client and 2 others have all had this issue recently.  I am not sure what mod it is conflicting with.  I removed resource packs thinking maybe a new texture had made it disappear.  I have so many mods it would take a very long time to try and find which one causing it.

This is a sample of my server log after world has started.  I do not recognize seeing the "onDeathBarterDeath" previously

****************** Blame Report 1.17-4.0.0-fabric ******************

Failed to load structure nbt file from : charm:dungeons/plains_creeper/plains_creeper

The path represented by this is: data/charm/structures/dungeons/plains_creeper/plains_creeper.nbt
The calling Template Pool is: charm:dungeons/plains/starts
Most common cause is that there is a typo in this path to the nbt file.
Please let the mod author know about this so they can double check to make sure the path is correct.
A common mistake is putting the structure nbt file in the asset folder when it needs to go in data/structures folder.

[14:24:29] [User Authenticator #1/INFO]: UUID of player jaded3 is ******
[14:24:31] [Server thread/INFO]: jaded3[/****** logged in with entity id 460 at (-348.40915044851573, 71.0, 19.542683365027845)
[14:24:31] [Server thread/INFO]: multiplayer.player.joined
[14:24:31] [Server thread/INFO]: [STDOUT]: 1 air
[14:24:32] [Netty Epoll Server IO #4/INFO]: Player jaded3 joined with a matching carpet client
[14:24:37] [Server thread/WARN]: @Final field field_25883:Lnet/minecraft/class_4970$class_4973; in charm.mixins.json:more_portal_frames.AddValidPortalFrameBlocksMixin should be final
[14:25:49] [Server thread/INFO]: chat.type.admin
[14:25:52] [Server thread/FATAL]: Error executing task on Server

java.lang.ArithmeticException: / by zero
at net.minecraft.class_1309.handler$dfn000$onDeathBarterDeath(class_1309.java:36748) ~[intermediary-server.jar:?]
at net.minecraft.class_1309.method_6095(class_1309.java) ~[intermediary-server.jar:?]
at net.minecraft.class_1309.method_5643(class_1309.java:1172) ~[intermediary-server.jar:?]
at net.minecraft.class_1657.method_5643(class_1657.java:918) ~[intermediary-server.jar:?]
at net.minecraft.class_3222.method_5643(class_3222.java:667) ~[intermediary-server.jar:?]
at net.minecraft.class_1309.method_5747(class_1309.java:1515) ~[intermediary-server.jar:?]
at net.minecraft.class_1657.method_5747(class_1657.java:1703) ~[intermediary-server.jar:?]
at net.minecraft.class_2248.method_9554(class_2248.java:464) ~[intermediary-server.jar:?]
at net.minecraft.class_1297.method_5623(class_1297.java:1153) ~[intermediary-server.jar:?]
at net.minecraft.class_1309.method_5623(class_1309.java:318) ~[intermediary-server.jar:?]
at net.minecraft.class_3222.method_14207(class_3222.java:972) ~[intermediary-server.jar:?]
at net.minecraft.class_3244.method_12063(class_3244.java:945) ~[intermediary-server.jar:?]
at net.minecraft.class_2828.method_12272(class_2828.java:114) ~[intermediary-server.jar:?]
at net.minecraft.class_2828$class_2829.method_11054(class_2828.java:42) ~[intermediary-server.jar:?]
at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:783) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:167) ~[intermediary-server.jar:?]
at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:765) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:759) ~[intermediary-server.jar:?]
at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:744) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.handler$bpd000$modifiedRunLoop(MinecraftServer.java:7402) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274) ~[intermediary-server.jar:?]
at java.lang.Thread.run(Unknown Source) [?:?]
[14:25:57] [Server thread/INFO]: [STDOUT]: removing undo from player: jaded3
[14:25:57] [Server thread/INFO]: [STDOUT]: 1 air
[14:26:09] [Server thread/INFO]: chat.type.admin
[14:26:24] [Server thread/INFO]: jaded3 lost connection: multiplayer.disconnect.generic
[14:26:24] [Server thread/INFO]: multiplayer.player.left
[14:26:24] [Server thread/INFO]: [STDOUT]: removing undo from player: jaded3
[14:28:57] [Server thread/INFO]: [Multiplayer Sleep] saver write start
[14:28:57] [Server thread/INFO]: [Multiplayer Sleep] saver write over

**Comment by KavisKryptic** [comment]
I'm also having this issue

**Comment by SpiffyJUNIOR** [comment]
Same issue, except in my case only the glow effect showed, and it also crashed my game when i tried to pick it up.
