### ISSUE TITLE
Charm1.17-3.3.1 incompatibility with hydrogen?

### ISSUE THREAD

**Issue by WANGCHIENCHIH** [svenhjol/Charm#632]
Read me first!
1. Is your issue about the Forge version of Charm? Please report your issue here: https://github.com/svenhjol/CharmForge/issues
2. We don't support OptiFabric! Please check that the problem still occurs if you remove OptiFabric from your mods.
3. Don't use the bug report to suggest new features or behavior.

Versions
* Charm version - e.g. `1.17-3.3.1`
* Minecraft version - e.g. `1.17.1`
* hydrogen - e.g. `mc1.17.1-0.3.1`
Description

update charm from 1.17-3.3.0 to 1.17-3.3.1, launch game,and crash

logs:
=========================================================
[07:19:12] [main/INFO]: Loading for game Minecraft 1.17.1
[07:19:12] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b446313, also found 0.3.0+a02b44633d, 0.3.0+a02b446318, 0.3.0+c88702897d
 - Conflicting versions found for fabric-key-binding-api-v1: used 1.0.4+a02b446318, also found 1.0.4+a02b44633d
 - Conflicting versions found for fabric-resource-loader-v0: used 0.4.7+b7ab6121d5, also found 0.4.7+b7ab61213d, 0.4.7+b7ab612113, 0.4.7+b7ab612118
 - Conflicting versions found for fabric-rendering-data-attachment-v1: used 0.1.5+a02b446313, also found 0.1.5+a02b446318
 - Conflicting versions found for fabric-rendering-fluids-v1: used 0.1.13+a02b446318, also found 0.1.13+a02b446313
 - Conflicting versions found for fabric-lifecycle-events-v1: used 1.4.4+a02b44633d, also found 1.4.4+a02b446318
 - Conflicting versions found for fabric-screen-api-v1: used 1.0.4+155f865c18, also found 1.0.4+198a96213d
 - Mod 'BetterF3' (betterf3) recommends version 2.0.0.* of mod 'Mod Menu' (modmenu), but a non-matching version is present: 2.0.2!
	 - You must install version 2.0.0.* of 'Mod Menu' (modmenu).
	 - Mod 'Mod Menu' (modmenu) v2.0.2 is being loaded from the user's mod directory.
[07:19:12] [main/INFO]: [FabricLoader] Loading 138 mods:
	- advanced_runtime_resource_pack@0.4.3
	- architectury@2.2.21
	- betterf3@1.1.5
	- bettermineshafts@1.17-1.0.0
	- bettersodiumvideosettingsbutton@2.0.0
	- betterstrongholds@1.17-1.1
	- carpet@1.4.44
	- carpet-extra@1.4.43
	- carpet-tis-addition@1.20.0+build.633
	- charm@3.3.1
	- cloth-api@2.0.54
	- cloth-basic-math@0.5.1
	- cloth-client-events-v0@2.0.54
	- cloth-common-events-v1@2.0.54
	- cloth-config2@5.0.34
	- cloth-datagen-api-v1@2.0.54
	- cloth-scissors-api-v1@2.0.54
	- cloth-utils-v1@2.0.54
	- com_electronwill_night-config_core@3.6.2
	- com_electronwill_night-config_toml@3.6.2
	- com_moandjiezana_toml_toml4j@0.7.2
	- com_squareup_okhttp3_okhttp@3.12.12
	- com_squareup_okio_okio@1.15.0
	- com_velocitypowered_velocity-native@1.1.0-SNAPSHOT
	- controlling@1.1.2
	- ctm@0.5.0+1.17
	- cullleaves@2.2.0
	- disable_custom_worlds_advice@1.3
	- enchantmentdescriptions@3.0.11
	- enhancedblockentities@0.4.1+1.17
	- entityculling@1.3.3
	- fabric@0.37.0+1.17
	- fabric-api-base@0.3.0+a02b446313
	- fabric-api-lookup-api-v1@1.2.0+2b5c62d018
	- fabric-biome-api-v1@3.1.11+c345aea818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.2+6cefd57718
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+a02b446318
	- fabric-content-registries-v0@0.2.2+a02b446318
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.1.0+a02b446318
	- fabric-events-interaction-v0@0.4.9+a722d8c018
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+6cefd57718
	- fabric-item-api-v1@1.2.4+a02b446318
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+a02b446318
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-language-kotlin@1.6.2+kotlin.1.5.20
	- fabric-lifecycle-events-v1@1.4.4+a02b44633d
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.12+6cefd57718
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+b7ab612118
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+5f02c96918
	- fabric-renderer-indigo@0.4.8+a02b446318
	- fabric-renderer-registries-v1@3.2.0+a02b446318
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446313
	- fabric-rendering-fluids-v1@0.1.13+a02b446318
	- fabric-rendering-v0@1.1.2+92519afa18
	- fabric-rendering-v1@1.6.0+a02b446318
	- fabric-resource-loader-v0@0.4.7+b7ab6121d5
	- fabric-screen-api-v1@1.0.4+155f865c18
	- fabric-screen-handler-api-v1@1.1.8+a02b446318
	- fabric-structure-api-v1@1.1.12+6cefd57718
	- fabric-tag-extensions-v0@1.1.4+a02b446318
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
	- fabric-transfer-api-v1@1.0.0+3fe3c3f518
	- fabricloader@0.11.6
	- fastfurnace@1.17-3.0
	- ferritecore@3.0.1
	- fiber@0.23.0-2
	- fpsdisplay@1.4.1+1.17
	- healthcare@1.0.7
	- hydrogen@0.3
	- indium@1.0.0+rev.beb4972
	- ingameime@1.6.4
	- inventoryprofilesnext@0.8.3
	- io_socket_engine_io-client@2.0.0
	- io_socket_socket_io-client@2.0.1
	- iris@1.1.0+rev.e110d24
	- jankson@3.0.1+j1.2.0
	- java@16
	- krypton@0.1.4
	- lambdynlights@2.0.1+1.17
	- libgui@4.1.0+1.17
	- libninepatch@1.1.0
	- libzoomer@0.2.1+1.17
	- lightoverlay@6.0.0
	- lithium@0.7.3
	- megane@5.1.1
	- megane-base@5.1.1
	- megane-runtime@5.1.1
	- megane-vanilla@5.1.1+1.17.1
	- minecraft@1.17.1
	- modmenu@2.0.2
	- morevillagers-fabric@2.0.4-SNAPSHOT
	- mostructures@1.2.1-1.17
	- nethermap@1.4.0-1.17.1
	- notenoughcrashes@3.3.1+1.17
	- okzoomer@5.0.0-beta.2+1.17
	- omega-config@1.0.8
	- org_aperlambda_lambdajcommon@1.8.1
	- org_jetbrains_kotlin_kotlin-reflect@1.5.20
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.20
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.20
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.20
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.0
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.0
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.1
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.1
	- org_json_json@20090211
	- particlerain@1.3.1
	- repurposed_structures@2.1.1+1.17.1
	- roughlyenoughitems@6.0.264-alpha
	- rpmtw_update_mod@1.2.1
	- satin@1.6.1
	- seasons@1.2.2-BETA+1.17
	- smoothboot@1.16.5-1.6.0
	- sodium@0.3.0+IRIS1-build.70
	- spruceui@3.2.0+1.17
	- starlight@1.0.0-RC3+fabric.2b7d7ae
	- statuseffecttimer@1.0.3
	- stoneholm@1.3
	- stonevaults@1.0.0
	- wthit@3.7.0
	- xaerominimap@21.14.0
	- xaeroworldmap@1.15.0.1
	- yungsapi@1.17-Fabric-13
[07:19:12] [main/WARN]: Mod `xaeroworldmap` (1.15.0.1) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[07:19:19] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/jameswang/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[07:19:19] [main/INFO]: Compatibility level set to JAVA_16
[07:19:23] [main/INFO]: Loaded configuration file for Sodium: 28 options available, 0 override(s) found
[07:19:23] [main/INFO]: Loaded configuration file for Lithium: 80 options available, 1 override(s) found
[07:19:24] [main/WARN]: [Satin] Sodium is present, custom block renders may not work
[07:19:24] [main/INFO]: [MixinConfig] Not adding potion_of_hogsbane.PreventAttackingHoglinMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding devenv.FixDevAuthSpamMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding auto_restock.AddStatWhenCompostedMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding variant_chests.FetchCustomChestTextureMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding parrots_stay_on_shoulder.KeepShoulderEntitiesMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding gentle_potion_particles.RenderTranslucentParticleMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding chickens_drop_feathers.DropFeatherMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding feather_falling_crops.PreventTramplingMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding variant_ladders.ClimbTrapdoorMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding extract_enchantments.UpdateGrindstoneOutputMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding auto_restock.AddStatWhenAnimalConsumedMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding colored_glints.GetItemMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding collection_enchantment.TryBreakBlockMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding aerial_affinity_enchantment.AllowBlockBreakMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding colored_glints.GetElytraMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding block_of_ender_pearls.PreventRandomTeleportMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding quadrants.RotateBlockBeforePlaceMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding potion_of_hogsbane.PreventAttackingAiMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding extract_enchantments.ShowGrindstoneCostMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding more_portal_frames.AddValidPortalFrameBlocksMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding extract_enchantments.AddCustomGrindstoneSlotsMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding colored_glints.GetCustomRenderLayersMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding colored_glints.GetArmorStackMixin
[07:19:24] [main/INFO]: [MixinConfig] Not adding collection_enchantment.AddDroppedItemToInventoryMixin
[07:19:24] [main/WARN]: @Mixin target net/minecraft/class_631$class_3681 is public in sodium.mixins.json:features.chunk_rendering.MixinClientChunkManager$MixinClientChunkMap and should be specified in value
[07:19:24] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[07:19:24] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[07:19:25] [main/WARN]: @Mixin target net/minecraft/class_4970$class_4971$class_3752 is public in ferritecore.blockstatecache.mixin.json:BlockStateCacheAccess and should be specified in value
[07:19:25] [main/FATAL]: Mixin prepare failed preparing util.MixinIdentifier in hydrogen.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: hydrogen.mixins.json:util.MixinIdentifier target net.minecraft.class_2960 was loaded too early.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: hydrogen.mixins.json:util.MixinIdentifier target net.minecraft.class_2960 was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:938) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:872) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:648) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:514) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.11.6.jar:0.9.4+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.lambda$getOrCreate$0(EntrypointStorage.java:106) ~[fabric-loader-0.11.6.jar:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[?:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:104) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:191) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:143) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[07:19:25] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[07:19:25] [main/INFO]: I used the json to destroy the json

**Comment by svenhjol** [comment]
A new version was released due to some compatibility issues with low-level mods: https://github.com/svenhjol/Charm/releases/download/3.3.2/charm-fabric-1.17-3.3.2.jar.  It's also submitted to curseforge and should be up there soon.

**Comment by WANGCHIENCHIH** [comment]
big thanks,after update to 1.17-3.3.2,it works!!!
