### ISSUE TITLE
Crash on 1.18.1

### ISSUE THREAD

**Issue by 3prm3** [svenhjol/Charm#727]
[04/01/2022 15:08:29 PM] [main/WARN] Method overwrite conflict for method_9522 in sodium.mixins.json:features.render_layer.leaves.MixinLeavesBlock, previously written by eu.midnightdust.cullleaves.mixin.MixinLeavesBlock. Skipping method.
[04/01/2022 15:08:32 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.12)
[04/01/2022 15:08:32 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610)
[04/01/2022 15:08:32 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[04/01/2022 15:08:32 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[04/01/2022 15:08:32 PM] Caused by: java.lang.ExceptionInInitializerError
[04/01/2022 15:08:32 PM] 	at net.minecraft.block.SnowyBlock.<clinit>(SnowyBlock:14)
[04/01/2022 15:08:32 PM] 	at net.minecraft.block.Blocks.<clinit>(Blocks:111)
[04/01/2022 15:08:32 PM] 	at net.minecraft.world.gen.carver.CarverDebugConfig.<clinit>(CarverDebugConfig:9)
[04/01/2022 15:08:32 PM] 	at net.minecraft.world.gen.carver.CarverConfig.method_33968(CarverConfig:16)
[04/01/2022 15:08:32 PM] 	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
[04/01/2022 15:08:32 PM] 	at net.minecraft.world.gen.carver.CarverConfig.<clinit>(CarverConfig:12)
[04/01/2022 15:08:32 PM] 	at net.minecraft.world.gen.carver.Carver.<clinit>(Carver:31)
[04/01/2022 15:08:32 PM] 	at net.minecraft.world.gen.carver.ConfiguredCarvers.<clinit>(ConfiguredCarvers:18)
[04/01/2022 15:08:32 PM] 	at net.minecraft.util.registry.BuiltinRegistries.method_30572(BuiltinRegistries:46)
[04/01/2022 15:08:32 PM] 	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:78)
[04/01/2022 15:08:32 PM] 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
[04/01/2022 15:08:32 PM] 	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:77)
[04/01/2022 15:08:32 PM] 	at net.minecraft.util.registry.Registry.<clinit>(Registry:269)
[04/01/2022 15:08:32 PM] 	at net.minecraft.Bootstrap.initialize(Bootstrap:49)
[04/01/2022 15:08:32 PM] 	at net.minecraft.client.main.Main.main(Main:155)
[04/01/2022 15:08:32 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04/01/2022 15:08:32 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[04/01/2022 15:08:32 PM] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04/01/2022 15:08:32 PM] 	at java.lang.reflect.Method.invoke(Method.java:568)
[04/01/2022 15:08:32 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
[04/01/2022 15:08:32 PM] 	... 2 more
[04/01/2022 15:08:32 PM] Caused by: java.lang.IllegalArgumentException: Multiple values have the same name 'amethyst'
[04/01/2022 15:08:32 PM] 	at net.minecraft.state.property.EnumProperty.<init>(EnumProperty:26)
[04/01/2022 15:08:32 PM] 	at net.minecraft.state.property.EnumProperty.of(EnumProperty:82)
[04/01/2022 15:08:32 PM] 	at net.minecraft.state.property.EnumProperty.of(EnumProperty:74)
[04/01/2022 15:08:32 PM] 	at net.minecraft.state.property.EnumProperty.of(EnumProperty:70)
[04/01/2022 15:08:32 PM] 	at net.minecraft.state.property.Properties.<clinit>(Properties:136)
[04/01/2022 15:08:32 PM] 	... 22 more
[04/01/2022 15:08:32 PM] [main/ERROR] Minecraft has crashed!
[04/01/2022 15:08:33 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
[04/01/2022 15:08:33 PM] Checking for updated files!

**Comment by sdaddy** [comment]
Are you trying to run the 1.17.1 release on 1.18.1?

**Comment by 3prm3** [comment]
No, it's a build of the 1.18 version

**Comment by sdaddy** [comment]
Did you build it yourself, or was the beta released somewhere?

**Comment by 3prm3** [comment]
I built it myself

**Comment by 3prm3** [comment]
Newer crash:
[07/01/2022 14:40:37 PM] [Render thread/ERROR] Critical injection failure: LVT in net/minecraft/class_634::method_11112(Lnet/minecraft/class_2604;)V has incompatible changes at opcode 67 in callback charm.mixins.json:event.ClientSpawnEntityMixin->@Inject::hookOnEntitySpawn(Lnet/minecraft/class_2604;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_1299;)V from mod charm.Available: []
[07/01/2022 14:40:37 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.12)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.createNativeModuleInfo(WinNativeModuleUtil:62)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.collectNativeModules(WinNativeModuleUtil:48)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.method_37968(WinNativeModuleUtil:132)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.crash.CrashReportSection.add(CrashReportSection:84)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.addDetailTo(WinNativeModuleUtil:131)
[07/01/2022 14:40:37 PM] 	at net.minecraft.client.main.Main.main(Main:207)
[07/01/2022 14:40:37 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07/01/2022 14:40:37 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[07/01/2022 14:40:37 PM] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07/01/2022 14:40:37 PM] 	at java.lang.reflect.Method.invoke(Method.java:568)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[07/01/2022 14:40:37 PM] [Render thread/INFO] Failed to find module info for C:\Users\HP\AppData\Local\Temp\lwjglHP\3.2.2-build-10\lwjgl.dll
[07/01/2022 14:40:37 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.12)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.createNativeModuleInfo(WinNativeModuleUtil:62)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.collectNativeModules(WinNativeModuleUtil:48)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.method_37968(WinNativeModuleUtil:132)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.crash.CrashReportSection.add(CrashReportSection:84)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.addDetailTo(WinNativeModuleUtil:131)
[07/01/2022 14:40:37 PM] 	at net.minecraft.client.main.Main.main(Main:207)
[07/01/2022 14:40:37 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07/01/2022 14:40:37 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[07/01/2022 14:40:37 PM] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07/01/2022 14:40:37 PM] 	at java.lang.reflect.Method.invoke(Method.java:568)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[07/01/2022 14:40:37 PM] [Render thread/INFO] Failed to find module info for C:\Users\HP\AppData\Local\Temp\lwjglHP\3.2.2-build-10\glfw.dll
[07/01/2022 14:40:37 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.12)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.createNativeModuleInfo(WinNativeModuleUtil:62)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.collectNativeModules(WinNativeModuleUtil:48)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.method_37968(WinNativeModuleUtil:132)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.crash.CrashReportSection.add(CrashReportSection:84)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.addDetailTo(WinNativeModuleUtil:131)
[07/01/2022 14:40:37 PM] 	at net.minecraft.client.main.Main.main(Main:207)
[07/01/2022 14:40:37 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07/01/2022 14:40:37 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[07/01/2022 14:40:37 PM] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07/01/2022 14:40:37 PM] 	at java.lang.reflect.Method.invoke(Method.java:568)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[07/01/2022 14:40:37 PM] [Render thread/INFO] Failed to find module info for C:\Users\HP\AppData\Local\Temp\lwjglHP\3.2.2-build-10\lwjgl_opengl.dll
[07/01/2022 14:40:37 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.12)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.createNativeModuleInfo(WinNativeModuleUtil:62)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.collectNativeModules(WinNativeModuleUtil:48)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.method_37968(WinNativeModuleUtil:132)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.crash.CrashReportSection.add(CrashReportSection:84)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.addDetailTo(WinNativeModuleUtil:131)
[07/01/2022 14:40:37 PM] 	at net.minecraft.client.main.Main.main(Main:207)
[07/01/2022 14:40:37 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07/01/2022 14:40:37 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[07/01/2022 14:40:37 PM] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07/01/2022 14:40:37 PM] 	at java.lang.reflect.Method.invoke(Method.java:568)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[07/01/2022 14:40:37 PM] [Render thread/INFO] Failed to find module info for C:\Users\HP\AppData\Local\Temp\lwjglHP\3.2.2-build-10\lwjgl_stb.dll
[07/01/2022 14:40:37 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.12)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.createNativeModuleInfo(WinNativeModuleUtil:62)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.collectNativeModules(WinNativeModuleUtil:48)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.method_37968(WinNativeModuleUtil:132)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.crash.CrashReportSection.add(CrashReportSection:84)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.addDetailTo(WinNativeModuleUtil:131)
[07/01/2022 14:40:37 PM] 	at net.minecraft.client.main.Main.main(Main:207)
[07/01/2022 14:40:37 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07/01/2022 14:40:37 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[07/01/2022 14:40:37 PM] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07/01/2022 14:40:37 PM] 	at java.lang.reflect.Method.invoke(Method.java:568)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[07/01/2022 14:40:37 PM] [Render thread/INFO] Failed to find module info for C:\Users\HP\AppData\Local\Temp\lwjglHP\3.2.2-build-10\OpenAL.dll
[07/01/2022 14:40:37 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.12)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.createNativeModuleInfo(WinNativeModuleUtil:62)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.collectNativeModules(WinNativeModuleUtil:48)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.method_37968(WinNativeModuleUtil:132)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.crash.CrashReportSection.add(CrashReportSection:84)
[07/01/2022 14:40:37 PM] 	at net.minecraft.util.WinNativeModuleUtil.addDetailTo(WinNativeModuleUtil:131)
[07/01/2022 14:40:37 PM] 	at net.minecraft.client.main.Main.main(Main:207)
[07/01/2022 14:40:37 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07/01/2022 14:40:37 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[07/01/2022 14:40:37 PM] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07/01/2022 14:40:37 PM] 	at java.lang.reflect.Method.invoke(Method.java:568)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[07/01/2022 14:40:37 PM] [Render thread/INFO] Failed to find module info for **USERSDIR**\temp\natives-06a41e0d597642b98d11b38a3a7b7c96\SAPIWrapper_x64.dll
[07/01/2022 14:40:37 PM] ---- Minecraft Crash Report ----
[07/01/2022 14:40:37 PM] // But it works on my machine.
[07/01/2022 14:40:37 PM] 
[07/01/2022 14:40:37 PM] Time: 1/7/22, 2:40 PM
[07/01/2022 14:40:37 PM] Description: Initializing game
[07/01/2022 14:40:37 PM] 
[07/01/2022 14:40:37 PM] java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_634 failed
[07/01/2022 14:40:37 PM] 	at net.minecraft.class_310.handler$ecj000$onReturn(class_310.java:17489)
[07/01/2022 14:40:37 PM] 	at net.minecraft.class_310.<init>(class_310.java:637)
[07/01/2022 14:40:37 PM] 	at net.minecraft.client.main.Main.main(Main.java:199)
[07/01/2022 14:40:37 PM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07/01/2022 14:40:37 PM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[07/01/2022 14:40:37 PM] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07/01/2022 14:40:37 PM] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[07/01/2022 14:40:37 PM] Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_634 failed
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
[07/01/2022 14:40:37 PM] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[07/01/2022 14:40:37 PM] 	... 10 more
[07/01/2022 14:40:37 PM] Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[07/01/2022 14:40:37 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[07/01/2022 14:40:37 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
[07/01/2022 14:40:37 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
[07/01/2022 14:40:37 PM] 	at com.astrazoey.indexed.TransformerMixinPlugin$ProxyMixinTransformer.transformClassBytes(TransformerMixinPlugin.java:123)
[07/01/2022 14:40:37 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
[07/01/2022 14:40:37 PM] 	... 13 more
[07/01/2022 14:40:37 PM] Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_634::method_11112(Lnet/minecraft/class_2604;)V has incompatible changes at opcode 67 in callback charm.mixins.json:event.ClientSpawnEntityMixin->@Inject::hookOnEntitySpawn(Lnet/minecraft/class_2604;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_1299;)V from mod charm.
[07/01/2022 14:40:37 PM]  Expected: [Lnet/minecraft/class_1299;]
[07/01/2022 14:40:37 PM]     Found: []
[07/01/2022 14:40:37 PM] Available: []
[07/01/2022 14:40:37 PM] 	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:545)
[07/01/2022 14:40:37 PM] 	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:495)
[07/01/2022 14:40:37 PM] 	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
[07/01/2022 14:40:37 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
[07/01/2022 14:40:37 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1374)
[07/01/2022 14:40:37 PM] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
[07/01/2022 14:40:37 PM] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
[07/01/2022 14:40:37 PM] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[07/01/2022 14:40:37 PM] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
[07/01/2022 14:40:37 PM] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
[07/01/2022 14:40:37 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[07/01/2022 14:40:37 PM] 	... 17 more
[07/01/2022 14:40:37 PM] 
[07/01/2022 14:40:37 PM] 
[07/01/2022 14:40:37 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[07/01/2022 14:40:37 PM] ---------------------------------------------------------------------------------------
[07/01/2022 14:40:37 PM] 
[07/01/2022 14:40:37 PM] -- Head --
[07/01/2022 14:40:37 PM] Thread: Render thread
[07/01/2022 14:40:37 PM] Stacktrace:
[07/01/2022 14:40:37 PM] 	at net.minecraft.class_310.handler$ecj000$onReturn(class_310.java:17489)
[07/01/2022 14:40:37 PM] 	at net.minecraft.class_310.<init>(class_310.java:637)
[07/01/2022 14:40:38 PM] 
[07/01/2022 14:40:38 PM] -- Initialization --
[07/01/2022 14:40:38 PM] Details:
[07/01/2022 14:40:38 PM] 	Modules: 
[07/01/2022 14:40:38 PM] 		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[07/01/2022 14:40:38 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.

**Comment by jockrint** [comment]
Did you found a solution?

**Comment by 3prm3** [comment]
Yeah

Made a new group of mods
