### ISSUE TITLE
Broken advancement filtering in 1.18

### ISSUE THREAD

**Issue by magneticflux-** [svenhjol/Charm#729]
Versions
* Charm version - e.g. `4.0.0`
* Minecraft version - e.g. `1.18.1`

Description:
Advancements are not filtered properly.

Optional: Steps To Reproduce
Join a world with an advancement-adding option disabled.

Optional: Stacktrace/Screenshots
```
[14:49:42] [Render thread/FATAL]: Error executing task on Client
java.lang.UnsupportedOperationException: null
	at com.google.common.collect.ImmutableMap.remove(ImmutableMap.java:851) ~[guava-31.0.1-jre.jar:?]
	at svenhjol.charm.helper.AdvancementHelper.lambda$filterAdvancements$4(AdvancementHelper.java:45) ~[charm-fabric-1.18-4.0.0.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at svenhjol.charm.helper.AdvancementHelper.lambda$filterAdvancements$5(AdvancementHelper.java:43) ~[charm-fabric-1.18-4.0.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at svenhjol.charm.helper.AdvancementHelper.filterAdvancements(AdvancementHelper.java:26) ~[charm-fabric-1.18-4.0.0.jar:?]
	at net.minecraft.class_163.handler$bbp000$hookAdd(class_163.java:534) ~[client-intermediary.jar:?]
	at net.minecraft.class_163.method_711(class_163.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_632.method_2861(class_632.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11130(class_634.java:1208) ~[client-intermediary.jar:?]
	at net.minecraft.class_2779.method_11925(class_2779.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_2779.method_11054(class_2779.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1080) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

My quick fix:
```patch
Index: src/main/java/svenhjol/charm/mixin/helper/FilterAdvancementsMixin.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/java/svenhjol/charm/mixin/helper/FilterAdvancementsMixin.java b/src/main/java/svenhjol/charm/mixin/helper/FilterAdvancementsMixin.java
--- a/src/main/java/svenhjol/charm/mixin/helper/FilterAdvancementsMixin.java	(revision 430b2c1e2b67ffa1c55305e6afcd5e647755c779)
+++ b/src/main/java/svenhjol/charm/mixin/helper/FilterAdvancementsMixin.java	(date 1641675898721)
@@ -1,5 +1,6 @@
 package svenhjol.charm.mixin.helper;
 
+import com.google.common.collect.ImmutableMap;
 import net.minecraft.advancements.Advancement;
 import net.minecraft.advancements.AdvancementList;
 import net.minecraft.resources.ResourceLocation;
@@ -31,6 +32,8 @@
         )
     )
     private void hookAdd(Map<ResourceLocation, Advancement.Builder> map, CallbackInfo ci) {
-        AdvancementHelper.filterAdvancements(map);
+        if (!(map instanceof ImmutableMap<ResourceLocation, Advancement.Builder>)) {
+            AdvancementHelper.filterAdvancements(map);
+        }
     }
 }
```

**Comment by FynnWaelsing** [comment]
1.18.2 is the only currently supported version of Charm. Please update to the 1.18.2 version and repost this issue if it persists.
