### ISSUE TITLE
Advancements screen breaks on 1.18.2 

### ISSUE THREAD

**Issue by HerrahStrings** [svenhjol/Charm#749]
Effect: Advancements screen doesn't display any advancements (charm nor vanilla)
Reproduction steps;
1. Disable some charm features [charm config.zip](https://github.com/svenhjol/Charm/files/8301493/charm.config.zip)
2. Load up a new world
3. Achieve "on the go" and "stone age"
4. Open the advancements screen (there is no charm tab)
5. Reload the world
6. Open the advancements screen 
7. 
![image](https://user-images.githubusercontent.com/55819817/158936403-f7cf3d57-ca70-4dd4-801d-e7f0eeaabc23.png)

```
Java is version 17, using 64-bit architecture, from Eclipse Adoptium.
Mods:
  [✔️] advancementinfo-1.18.2-fabric0.47.10-1.3.1
  [✔️] charm-fabric-1.18-4.0.0
  [✔️] cloth-config-6.2.57-fabric
  [✔️] fabric-api-0.48.0+1.18.2
  [✔️] modmenu-3.1.0
  [✔️] notenoughcrashes-4.1.4+1.18.2-fabric

[15:14:25] [Render thread/ERROR]: Error executing task on Client
java.lang.UnsupportedOperationException: null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.2) ~[?:?]
	at com.google.common.collect.ImmutableMap.remove(ImmutableMap.java:851) ~[guava-31.0.1-jre.jar:?]
	at svenhjol.charm.helper.AdvancementHelper.lambda$filterAdvancements$4(AdvancementHelper.java:45) ~[charm-fabric-1.18-4.0.0.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at svenhjol.charm.helper.AdvancementHelper.lambda$filterAdvancements$5(AdvancementHelper.java:43) ~[charm-fabric-1.18-4.0.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at svenhjol.charm.helper.AdvancementHelper.filterAdvancements(AdvancementHelper.java:26) ~[charm-fabric-1.18-4.0.0.jar:?]
	at net.minecraft.advancement.AdvancementManager.handler$zcb000$hookAdd(AdvancementManager:534) ~[?:?]
	at net.minecraft.advancement.AdvancementManager.load(AdvancementManager:57) ~[?:?]
	at net.minecraft.client.network.ClientAdvancementManager.onAdvancements(ClientAdvancementManager:40) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onAdvancements(ClientPlayNetworkHandler:1211) ~[?:?]
	at net.minecraft.network.packet.s2c.play.AdvancementUpdateS2CPacket.apply(AdvancementUpdateS2CPacket:51) ~[?:?]
	at net.minecraft.network.packet.s2c.play.AdvancementUpdateS2CPacket.apply(AdvancementUpdateS2CPacket:16) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1085) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by ShellSnake** [comment]
Can confirm, this problem happened to me also
