### ISSUE TITLE
[1.18.2] Advancements are broken when Charm is installed

### ISSUE THREAD

**Issue by GalaxySynth** [svenhjol/Charm#781]
When I load the latest version of Charm [[charm-fabric-1.18-4.1.0.jar](https://www.curseforge.com/minecraft/mc-mods/charm/files/3764177)] I get this screen when I try to open advancements

Disabling Charm fixes the issue
![2022-05-02_13 22 17](https://user-images.githubusercontent.com/73800917/166303974-c1a24c60-826e-49e2-bbf6-c15119f68ff1.png)

**Comment by itsdinkd** [comment]
Here is the error log;

[21:17:31] [Render thread/ERROR]: Error executing task on Client
java.lang.UnsupportedOperationException: null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at com.google.common.collect.ImmutableMap.remove(ImmutableMap.java:851) ~[guava-31.0.1-jre.jar:?]
	at svenhjol.charm.helper.AdvancementHelper.lambda$filterAdvancements$4(AdvancementHelper.java:45) ~[charm-fabric-1.18-4.1.0.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at svenhjol.charm.helper.AdvancementHelper.lambda$filterAdvancements$5(AdvancementHelper.java:43) ~[charm-fabric-1.18-4.1.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at svenhjol.charm.helper.AdvancementHelper.filterAdvancements(AdvancementHelper.java:26) ~[charm-fabric-1.18-4.1.0.jar:?]
	at net.minecraft.advancement.AdvancementManager.handler$edh000$hookAdd(AdvancementManager:534) ~[?:?]
	at net.minecraft.advancement.AdvancementManager.load(AdvancementManager:57) ~[?:?]
	at net.minecraft.client.network.ClientAdvancementManager.onAdvancements(ClientAdvancementManager:40) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onAdvancements(ClientPlayNetworkHandler:1211) ~[?:?]
	at net.minecraft.network.packet.s2c.play.AdvancementUpdateS2CPacket.apply(AdvancementUpdateS2CPacket:51) ~[?:?]
	at net.minecraft.network.packet.s2c.play.AdvancementUpdateS2CPacket.apply(AdvancementUpdateS2CPacket:16) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1085) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [fabric-loader-0.14.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.2.jar:?]

**Comment by itsdinkd** [comment]
Steps to reproduce

go into game and /reload

**Comment by GalaxySynth** [comment]
Thanks for adding these to my issue, I had forgottten to, +1

**Comment by itsdinkd** [comment]
> Thanks for adding these to my issue, I had forgottten to, +1

No problem. you might be able to still use charm  by disabling the Advancement tree in the config until they fix the bug
![image](https://user-images.githubusercontent.com/35115304/166563634-066648eb-86b1-406b-a4db-62cce5ca21b9.png)

**Comment by FederAndInk** [comment]
Seems related to: #729 #734 #749 

There is even a PR: #738

Can we get this merged and fixed? Please folks.

**Comment by pajicadvance** [comment]
> > Thanks for adding these to my issue, I had forgottten to, +1
> 
> No problem. you might be able to still use charm by disabling the Advancement tree in the config until they fix the bug ![image](https://user-images.githubusercontent.com/35115304/166563634-066648eb-86b1-406b-a4db-62cce5ca21b9.png)

this didn't seem to help, the advancements screen is still empty. are my advancements corrupted because of this?

**Comment by Darathas** [comment]
> > > Thanks for adding these to my issue, I had forgottten to, +1
> > 
> > 
> > No problem. you might be able to still use charm by disabling the Advancement tree in the config until they fix the bug ![image](https://user-images.githubusercontent.com/35115304/166563634-066648eb-86b1-406b-a4db-62cce5ca21b9.png)
> 
> this didn't seem to help, the advancements screen is still empty. are my advancements corrupted because of this?

I disabled/uninstalled charm from my own world. Other than the usual missing stuff where Charm things were removed (like chests and things), everything else seemed to work like normal, achievements included. It primarily seems that Charm messes with how the game is pulling and displaying achievements right now.

**Comment by pajicadvance** [comment]
The mod author seems inactive so I compiled the mod by myself with the fix from #738 included. Advancements show up again and work correctly.
