### ISSUE TITLE
Game crashing upon death

### ISSUE THREAD

**Issue by HiGuysItsMeSussyBaka** [svenhjol/Charm#869]
I'm not sure why it's crashing. Can you try to diagnose the issue? I think it's something Charm is doing. I was killed by a vindicator when it crashed during a raid.
---- Minecraft Crash Report ----
// My bad.

Time: 2022-10-14 07:03:37
Description: Ticking entity

java.lang.ExceptionInInitializerError
	at net.minecraft.class_1309.handler$cbh000$tryUseTotem(class_1309.java:17661)
	at net.minecraft.class_1309.method_6095(class_1309.java)
	at net.minecraft.class_1309.method_5643(class_1309.java:1199)
	at net.minecraft.class_1657.method_5643(class_1657.java:952)
	at net.minecraft.class_3222.method_5643(class_3222.java:713)
	at net.minecraft.class_1308.method_6121(class_1308.java:1429)
	at net.minecraft.class_1366.method_6288(class_1366.java:152)
	at net.minecraft.class_1366.method_6268(class_1366.java:144)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:119)
	at net.minecraft.class_1355.method_6275(class_1355.java:110)
	at net.minecraft.class_1308.method_6023(class_1308.java:753)
	at net.minecraft.class_1309.method_6007(class_1309.java:2641)
	at net.minecraft.class_1308.method_6007(class_1308.java:553)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_3763.method_6007(class_3763.java:114)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1308.method_5773(class_1308.java:353)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Registry is already frozen
	at net.minecraft.class_2370.method_40269(class_2370.java:365)
	at net.minecraft.class_1792.<init>(class_1792.java:61)
	at net.minecraft.class_1738.<init>(class_1738.java:74)
	at net.nu11une.wardenloot.common.WLArmorItem.<init>(WLArmorItem.java:21)
	at net.nu11une.wardenloot.register.WLChestplate.<clinit>(WLChestplate.java:33)
	... 29 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1309.handler$cbh000$tryUseTotem(class_1309.java:17661)
	at net.minecraft.class_1309.method_6095(class_1309.java)
	at net.minecraft.class_1309.method_5643(class_1309.java:1199)
	at net.minecraft.class_1657.method_5643(class_1657.java:952)
	at net.minecraft.class_3222.method_5643(class_3222.java:713)
	at net.minecraft.class_1308.method_6121(class_1308.java:1429)
	at net.minecraft.class_1366.method_6288(class_1366.java:152)
	at net.minecraft.class_1366.method_6268(class_1366.java:144)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:119)
	at net.minecraft.class_1355.method_6275(class_1355.java:110)
	at net.minecraft.class_1308.method_6023(class_1308.java:753)
	at net.minecraft.class_1309.method_6007(class_1309.java:2641)
	at net.minecraft.class_1308.method_6007(class_1308.java:553)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_3763.method_6007(class_3763.java:114)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1308.method_5773(class_1308.java:353)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)

-- Entity being ticked --
Details:
	Entity Type: minecraft:vindicator (net.minecraft.class_1632)
	Entity ID: 9127
	Entity Name: Vindicator
	Entity's Exact location: -145.24, 87.00, -111.75
	Entity's Block location: World: (-146,87,-112), Section: (at 14,7,0 in -10,5,-7; chunk contains blocks -160,-64,-112 to -145,319,-97), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: -0.06, -0.08, 0.05
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['MarioBlock'/286, l='ServerLevel[terraria crossover (mimics)]', x=-146.22, y=87.00, z=-111.50]]
	Chunk stats: 2830
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,76,0), Section: (at 0,12,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1650562 game time, 2246246 day time
	Level name: terraria crossover (mimics)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 93964 (now: false), thunder time: 5284 (now: true)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 559507968 bytes (533 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 3 3250U with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.60
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: DriverVersion=30.0.13026.3
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 15281.04
	Virtual memory used (MB): 9938.13
	Swap memory total (MB): 9216.00
	Swap memory used (MB): 1111.17
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx2048m
	Fabric Mods: 
		balm-fabric: Balm 4.5.2+0
		basicshields: Basic Shields [Fabric] 1.4.0-pre2-1.19.2
			crowdin-translate: CrowdinTranslate 1.4+1.19
		better_bad_omen: Better Bad Omen 1.6.0
		betterbeacon: Better Beacons 1.0.8
		bettersculksensor: BetterSculkSensor 1.1.8
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmofundying: Charm of Undying 6.0.0+1.19.2
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		combatroll: Combat Roll 1.0.8+1.19
		dragonloot: DragonLoot 1.1.2
		enchantinginfuser: Enchanting Infuser 4.2.1
		explorerscompass: Explorer's Compass 1.19.2-2.2.0-fabric
		fabric-api: Fabric API 0.62.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.21+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.2+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.3.1+624e468e90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.0+b598f4ac90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.19+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.30+93d8cb8290
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.21+93d8cb8290
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.19+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.4+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.7+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.15+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.18+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.12+93d8cb8290
			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.11+c6af733c90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.13+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.21+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.15+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.23+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.12+a29562c890
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.0+93d8cb8290
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.27+93d8cb8290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-textures-v0: Fabric Textures (v0) 1.0.21+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabricloader: Fabric Loader 0.14.9
		fabricshieldlib: Fabric Shield Lib 1.6.0-1.19
			mm: Manningham Mills 2.3
		forgeconfigapiport: Forge Config API Port 4.2.6
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		geckolib3: Geckolib 3.1.22
			com_eliotlash_mclib_mclib: mclib 19
			com_eliotlash_molang_molang: molang 19
		harvest_scythes: Harvest Scythes 2.5.3
		icy-incitement: Icy Incitement 1.1.4+1.19.x
		infwithmend: Infinity with Mending 1.0.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		jei: Just Enough Items 11.3.0.262
		lithium: Lithium 0.8.3
		minecraft: Minecraft 1.19.2
		mob_catcher: Mob Catcher 1.2.13
		morebannerfeatures: More Banner Features 1.1.3
		phosphor: Phosphor 0.8.1
		player-animator: Player Animator 0.3.5
		probablychests: Probably Chests 0.5.5-1.19.2
		puzzleslib: Puzzles Lib 4.3.9
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		pvaf: Echo Rod 1.0.0
		ratsmischief: Rat's Mischief 1.4.0
		scout: Scout 1.1.1
		sculkhornid: Sculk Horn Mod 1.1.0-1.19.x
		shinyhorses: Shiny Horses 1.0.0
		silkspawners: SilkSpawners 1.1.2
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sonic_deflect: Sonic Deflect 1.0.1+1.19
		strawstatues: Straw Statues 4.0.1
		tinyskeletons: Tiny Skeletons 4.2.1
		trinkets: Trinkets 3.4.0
		veinmining: Vein Mining 1.0.0-beta.5+1.19.2
			spectrelib: SpectreLib 0.11.0+1.19
		wardenloot: Warden Loot 1.1.2-1.19.x
		waystones: Waystones 11.1.0
		xray: XrayMod 2.0.5
	Server Running: true
	Player Count: 1 / 8; [class_3222['MarioBlock'/286, l='ServerLevel[terraria crossover (mimics)]', x=-146.22, y=87.00, z=-111.50]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.19.2

**Comment by lxly9** [comment]
it does say wardenloot in the crash though

**Comment by lxly9** [comment]
try without wl and see if it works

**Comment by HiGuysItsMeSussyBaka** [comment]
k

**Comment by HiGuysItsMeSussyBaka** [comment]
alright, it worked. thanks. i was really looking forward to that trinket tho
