### ISSUE TITLE
Game crashes on launch

### ISSUE THREAD

**Issue by AssB0ys** [svenhjol/Charm#87]
The game crashes on launch with a following error:

> [13:37:21] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@4af9b705:
java.lang.ClassCastException: com.jaquadro.minecraft.storagedrawers.capabilities.DrawerItemHandler cannot be cast to net.minecraftforge.items.wrapper.InvWrapper
at svenhjol.charm.base.ASMHooks.canInsertItemIntoShulkerBox(ASMHooks.java:102) ~[ASMHooks.class:?]
at net.minecraftforge.items.ItemHandlerHelper.insertItem(ItemHandlerHelper.java:40) ~[ItemHandlerHelper.class:?]
at org.cyclops.commoncapabilities.ingredient.storage.IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.insert(IngredientComponentStorageWrapperHandlerItemStack.java:139) ~[IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.class:?]
at org.cyclops.commoncapabilities.ingredient.storage.IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.insert(IngredientComponentStorageWrapperHandlerItemStack.java:97) ~[IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.class:?]
at org.cyclops.integrateddynamics.core.network.IngredientChannelAdapter.insert(IngredientChannelAdapter.java:133) ~[IngredientChannelAdapter.class:?]
at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.insertIntoNetwork(PartTypeInterfaceCrafting.java:271) ~[PartTypeInterfaceCrafting.class:?]
at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.update(PartTypeInterfaceCrafting.java:220) ~[PartTypeInterfaceCrafting.class:?]
at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.update(PartTypeInterfaceCrafting.java:89) ~[PartTypeInterfaceCrafting.class:?]
at org.cyclops.integrateddynamics.core.network.PartNetworkElement.update(PartNetworkElement.java:134) ~[PartNetworkElement.class:?]
at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:408) ~[Network.class:?]
at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:65) ~[TickHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_960_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) [FMLCommonHandler.class:?]
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712) [MinecraftServer.class:?]
at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:256) [chd.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[13:37:21] [Server thread/ERROR] [FML]: Index: 14 Listeners:
[13:37:21] [Server thread/ERROR] [FML]: 0: NORMAL
[13:37:21] [Server thread/ERROR] [FML]: 1: ASM: class dan200.computercraft.shared.util.TickScheduler tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 2: ASM: class dan200.computercraft.shared.proxy.ComputerCraftProxyCommon$ForgeHandlers onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 3: ASM: class com.feed_the_beast.mods.ftbbackups.FTBBackups onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 4: ASM: net.minecraftforge.common.ForgeInternalHandler@46605225 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 5: ASM: mcjty.lostsouls.ForgeEventHandlers@7c8b4eab onTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 6: ASM: oreexcavation.handlers.EventHandler@6f3b7fc1 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 7: ASM: hellfirepvp.astralsorcery.common.auxiliary.tick.TickManager@1cddf9ee serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 8: ASM: class thebetweenlands.common.handler.WorldEventHandler onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 9: ASM: class thebetweenlands.common.capability.base.EntityCapabilityHandler onServerTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 10: ASM: thebetweenlands.common.world.biome.spawning.MobSpawnHandler@6fb92d3a onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 11: ASM: class thebetweenlands.common.handler.EnvironmentEventOverridesHandler onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 12: ASM: Block{minecraft:air} tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 13: ASM: org.cyclops.evilcraft.core.fluid.WorldSharedTankCache@3087e663 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 14: ASM: org.cyclops.integrateddynamics.core.TickHandler@17c6849a onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 15: ASM: org.cyclops.integrateddynamics.core.NoteBlockEventReceiver@20509b1a onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 16: LOWEST
[13:37:21] [Server thread/ERROR] [FML]: 17: ASM: class codechicken.lib.internal.CCLLog onTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.ClassCastException: com.jaquadro.minecraft.storagedrawers.capabilities.DrawerItemHandler cannot be cast to net.minecraftforge.items.wrapper.InvWrapper
at svenhjol.charm.base.ASMHooks.canInsertItemIntoShulkerBox(ASMHooks.java:102) ~[ASMHooks.class:?]
at net.minecraftforge.items.ItemHandlerHelper.insertItem(ItemHandlerHelper.java:40) ~[ItemHandlerHelper.class:?]
at org.cyclops.commoncapabilities.ingredient.storage.IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.insert(IngredientComponentStorageWrapperHandlerItemStack.java:139) ~[IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.class:?]
at org.cyclops.commoncapabilities.ingredient.storage.IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.insert(IngredientComponentStorageWrapperHandlerItemStack.java:97) ~[IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.class:?]
at org.cyclops.integrateddynamics.core.network.IngredientChannelAdapter.insert(IngredientChannelAdapter.java:133) ~[IngredientChannelAdapter.class:?]
at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.insertIntoNetwork(PartTypeInterfaceCrafting.java:271) ~[PartTypeInterfaceCrafting.class:?]
at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.update(PartTypeInterfaceCrafting.java:220) ~[PartTypeInterfaceCrafting.class:?]
at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.update(PartTypeInterfaceCrafting.java:89) ~[PartTypeInterfaceCrafting.class:?]
at org.cyclops.integrateddynamics.core.network.PartNetworkElement.update(PartNetworkElement.java:134) ~[PartNetworkElement.class:?]
at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:408) ~[Network.class:?]
at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:65) ~[TickHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_960_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) ~[FMLCommonHandler.class:?]
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712) ~[MinecraftServer.class:?]
at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:256) ~[chd.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[13:37:21] [Server thread/WARN] [org.dimdev.utils.ModIdentifier]: Failed to identify net.minecraftforge.fml.common.eventhandler.ASMEventHandler_960_TickHandler_onTick_TickEvent (untransformed name: net.minecraftforge.fml.common.eventhandler.ASMEventHandler_960_TickHandler_onTick_TickEvent)

I've created a bug report on the Integrated Dynamics issue tracker too - https://github.com/CyclopsMC/IntegratedDynamics/issues/737

It seems to be related to https://github.com/svenhjol/Charm/issues/86 also

Charm version: 1.1.10
Minecraft: 1.12.2
Forge: 14.23.5.2838

**Comment by svenhjol** [comment]
Please could you test this build and let me know if it still crashes: https://github.com/svenhjol/Charm/releases/download/1.12.2-1.1.11/Charm-1.12.2-1.1.11.jar

**Comment by AssB0ys** [comment]
Yes I've tested this build and the same error seem to still appear:

> [14:12:15] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@51c459b2:
java.lang.ClassCastException: com.jaquadro.minecraft.storagedrawers.capabilities.DrawerItemHandler cannot be cast to net.minecraftforge.items.wrapper.InvWrapper
	at svenhjol.charm.base.ASMHooks.canInsertItemIntoShulkerBox(ASMHooks.java:101) ~[ASMHooks.class:?]
	at net.minecraftforge.items.ItemHandlerHelper.insertItem(ItemHandlerHelper.java:40) ~[ItemHandlerHelper.class:?]
	at org.cyclops.commoncapabilities.ingredient.storage.IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.insert(IngredientComponentStorageWrapperHandlerItemStack.java:139) ~[IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.class:?]
	at org.cyclops.commoncapabilities.ingredient.storage.IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.insert(IngredientComponentStorageWrapperHandlerItemStack.java:97) ~[IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.class:?]
	at org.cyclops.integrateddynamics.core.network.IngredientChannelAdapter.insert(IngredientChannelAdapter.java:133) ~[IngredientChannelAdapter.class:?]
	at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.insertIntoNetwork(PartTypeInterfaceCrafting.java:271) ~[PartTypeInterfaceCrafting.class:?]
	at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.update(PartTypeInterfaceCrafting.java:220) ~[PartTypeInterfaceCrafting.class:?]
	at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.update(PartTypeInterfaceCrafting.java:89) ~[PartTypeInterfaceCrafting.class:?]
	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.update(PartNetworkElement.java:134) ~[PartNetworkElement.class:?]
	at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:408) ~[Network.class:?]
	at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:65) ~[TickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_960_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:256) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[14:12:15] [Server thread/ERROR] [FML]: Index: 14 Listeners:
[14:12:15] [Server thread/ERROR] [FML]: 0: NORMAL
[14:12:15] [Server thread/ERROR] [FML]: 1: ASM: class dan200.computercraft.shared.util.TickScheduler tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[14:12:15] [Server thread/ERROR] [FML]: 2: ASM: class dan200.computercraft.shared.proxy.ComputerCraftProxyCommon$ForgeHandlers onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[14:12:15] [Server thread/ERROR] [FML]: 3: ASM: class com.feed_the_beast.mods.ftbbackups.FTBBackups onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[14:12:15] [Server thread/ERROR] [FML]: 4: ASM: net.minecraftforge.common.ForgeInternalHandler@3597c039 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[14:12:15] [Server thread/ERROR] [FML]: 5: ASM: mcjty.lostsouls.ForgeEventHandlers@50a1509e onTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[14:12:15] [Server thread/ERROR] [FML]: 6: ASM: oreexcavation.handlers.EventHandler@5b56c601 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[14:12:15] [Server thread/ERROR] [FML]: 7: ASM: hellfirepvp.astralsorcery.common.auxiliary.tick.TickManager@412ba7f9 serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[14:12:15] [Server thread/ERROR] [FML]: 8: ASM: class thebetweenlands.common.handler.WorldEventHandler onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[14:12:15] [Server thread/ERROR] [FML]: 9: ASM: class thebetweenlands.common.capability.base.EntityCapabilityHandler onServerTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[14:12:15] [Server thread/ERROR] [FML]: 10: ASM: thebetweenlands.common.world.biome.spawning.MobSpawnHandler@4066cddc onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[14:12:15] [Server thread/ERROR] [FML]: 11: ASM: class thebetweenlands.common.handler.EnvironmentEventOverridesHandler onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[14:12:15] [Server thread/ERROR] [FML]: 12: ASM: Block{minecraft:air} tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[14:12:15] [Server thread/ERROR] [FML]: 13: ASM: org.cyclops.evilcraft.core.fluid.WorldSharedTankCache@262923ec onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[14:12:15] [Server thread/ERROR] [FML]: 14: ASM: org.cyclops.integrateddynamics.core.TickHandler@323bc94d onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[14:12:15] [Server thread/ERROR] [FML]: 15: ASM: org.cyclops.integrateddynamics.core.NoteBlockEventReceiver@40b8759e onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[14:12:15] [Server thread/ERROR] [FML]: 16: LOWEST
[14:12:15] [Server thread/ERROR] [FML]: 17: ASM: class codechicken.lib.internal.CCLLog onTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[14:12:15] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.ClassCastException: com.jaquadro.minecraft.storagedrawers.capabilities.DrawerItemHandler cannot be cast to net.minecraftforge.items.wrapper.InvWrapper
	at svenhjol.charm.base.ASMHooks.canInsertItemIntoShulkerBox(ASMHooks.java:101) ~[ASMHooks.class:?]
	at net.minecraftforge.items.ItemHandlerHelper.insertItem(ItemHandlerHelper.java:40) ~[ItemHandlerHelper.class:?]
	at org.cyclops.commoncapabilities.ingredient.storage.IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.insert(IngredientComponentStorageWrapperHandlerItemStack.java:139) ~[IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.class:?]
	at org.cyclops.commoncapabilities.ingredient.storage.IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.insert(IngredientComponentStorageWrapperHandlerItemStack.java:97) ~[IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.class:?]
	at org.cyclops.integrateddynamics.core.network.IngredientChannelAdapter.insert(IngredientChannelAdapter.java:133) ~[IngredientChannelAdapter.class:?]
	at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.insertIntoNetwork(PartTypeInterfaceCrafting.java:271) ~[PartTypeInterfaceCrafting.class:?]
	at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.update(PartTypeInterfaceCrafting.java:220) ~[PartTypeInterfaceCrafting.class:?]
	at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.update(PartTypeInterfaceCrafting.java:89) ~[PartTypeInterfaceCrafting.class:?]
	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.update(PartNetworkElement.java:134) ~[PartNetworkElement.class:?]
	at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:408) ~[Network.class:?]
	at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:65) ~[TickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_960_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:256) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Comment by svenhjol** [comment]
And this one... https://github.com/svenhjol/Charm/releases/download/1.12.2-1.1.12/Charm-1.12.2-1.1.12.jar

**Comment by AssB0ys** [comment]
No crashes or errors on launch with the 1.1.12 build. Thank you for the quick reply.

**Comment by svenhjol** [comment]
Thanks for testing!

**Comment by mattrix444** [comment]
hi sorry i know this is closed but thought id jump in, i was getting a similar crash involving shulker boxes but my client was only crashing when dying in hardcore. but i downloaded the 1.1.12 listed in this thread and the crash has stopped so thought id just mention :)
